# Curse of Dimensionality:
    -> when we add features in data then the model perfomence will increase but at the optimal point the perfomence of the model will decrease this is called COD.
    1> perfomence decreases.
    2> computationn increases.

### How to solve:
    -> Dimensinality Reduction:
            1.Feature selection
            2.Feature Extraction

# PCA: Principle Component Analysis
    -> It is feature extraction technique goal to reduce COD.
    -> Transform higher dimension data to lower dimension data.

### Benifit of using PCA:
    -> faster execution of the algorithm.
    -> visualization.

# variance: 
    -> variance help to know the spread of the data in any dataset.

![alt text](<Screenshot 2024-04-24 053341.png>)

# Projection:
    -> sare points ko project krna hai and sare points se length milega kyunki projection ek number(scalar) hoga.
    -> variance ko maximise krna hai.
    ->hm us  unit vector ko choose karenge jiske liye hamara variance maximum ho.

### How to calculate variance:
    -> variance on that unit vector.
![alt text](<Screenshot 2024-04-24 054013.png>)

-> hame us Unit vector ko find krna hai jiske liye variance maximum ho.

# Covariance and Covariance Matrix:
        -> It tells the relation between the X and Y.
### Covariance Matrix:
![alt text](<Screenshot 2024-04-24 054949.png>)
-> Covariance matrix sare axis pe spread batata hai.
-> also tells the relation between the two axis.

![alt text](<Screenshot 2024-04-24 055552.png>)

# Linear Transfomation, Eigen Vectors and Eigen Values:
    -> Metrices are linear Transformation, When we apply metrices on co-ordinate system then the all points of co-ordinate system will transform.
### Eigen Vectors:
    -> Jinka direction change nhi hota after transform,called Eigen vectors.
            -> A*vector(v)=Lamda*vector(v),here:lamda is eigen value

### Eigen value:
    -> koi bhi point  kitna strech kr raha hai after apply transformation (change in the magnitude of the point ).

# Step By Step Solution:
    1.Mean center.(in every direction)
    2.Find covariance matrix.
    3. find the eigen vector and eigen value fo covariance matrix.
    4. jiska eigen value sabse jayada hai wo principle component 1 banta hai jo usase kam hai wo PC2 banta hai and so on.


# How to transform points?
![alt text](<Screenshot 2024-04-24 062135.png>)

In [37]:
import numpy as np
import pandas as pd

In [38]:
np.random.seed(23)
mu_vec1=np.array([0,0,0])
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample=np.random.multivariate_normal(mu_vec1,cov_mat1,20)

df=pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target']=1

mu_vec2=np.array([1,1,1])
cov_mat2=np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample=np.random.multivariate_normal(mu_vec2,cov_mat2,20)
df1=pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target']=0

df=pd.concat([df,df1],ignore_index=True)
df=df.sample(40)

In [39]:
df.head()

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [40]:
import plotly.express as px
fig=px.scatter_3d(df,x=df['feature1'],y=df['feature2'],z=df['feature3'],
                  color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,line=dict(width=2,color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

In [41]:
# step1-Apply standered scaling
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()

df.iloc[:,0:3]=scalar.fit_transform(df.iloc[:,0:3])

In [42]:
# step2-find Covariance matrix

covariance_matrix=np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix: \n',covariance_matrix)

Covariance Matrix: 
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [43]:
# step 3- finding Eigon value and Eigon vector:
eigen_values,eigen_vectors=np.linalg.eig(covariance_matrix)

In [44]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [45]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [46]:
%pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch


class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)
fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df['feature1'], df['feature2'], df['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['feature1'].mean()], [df['feature2'].mean()], [df['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vectors.T:
    a = Arrow3D([df['feature1'].mean(), v[0]], [df['feature2'].mean(), v[1]], [df['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')

plt.show()

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

<Figure size 700x700 with 1 Axes>